"""init schema

Revision ID: d63868972843
Revises: 
Create Date: 2025-09-05 11:56:24.708752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63868972843'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('start_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('start_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('end_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('end_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('start_address', sa.String(length=255), nullable=True),
    sa.Column('end_address', sa.String(length=255), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('mode_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('co2_emissions', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cost_rupees', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('altitude', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('accuracy', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('speed', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_points')
    op.drop_table('trips')
    op.drop_table('users')
    # ### end Alembic commands ###
